[package]
name = "backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
axum-macros = "0.3.8"
dotenv = "0.15.0"
h3 = "0.0.3"
h3-quinn = "0.0.4"
hyper = { version = "0.14.27", features = ["full"] }
webtransport-quinn ={ git = "https://github.com/kelvinkirima014/webtransport-rs.git" }
tokio = { version = "1.33.0", features = ["full"] }
